CREATE OR REPLACE FORCE EDITIONABLE VIEW "APP_USERS_LOGIN" ("USER_ID", "USERNAME", "USER_NAME_EN", "USER_NAME_AR", "PASSWORD", "EMAIL", "PHONE", "IS_LOCKED", "USER_STATUS", "USER_NOTES", "USER_TYPE", "IS_OTP_SMS", "IS_MOBILE_APP", "DEFAULT_COMPANY_ID", "DEFAULT_BRANCH_ID", "DEVICE_UUID", "IS_CHANGE_PASSWORD", "IS_PASSWORD_CHANGED", "PASSWORD_CHANGE_DATE", "ALLOW_ATTENDANCE", "ALLOW_DAILIES", "EMPLOYEE_ID", "EMPLOYEE_CODE", "ID_NUMBER", "DATE_OF_BIRTH", "EMPLOYEE_NAME_AR", "EMPLOYEE_NAME_EN", "HIRE_DATE", "EMPLOYMENT_STATUS", "WORK_LOCATION", "SITE_ID", "CHECK_LOCATION", "EMPLOYEE_CATEGORY_ID", "EMPLOYEE_CATEGORY_NAME_EN", "EMPLOYEE_CATEGORY_NAME_AR", "EMPLOYEE_STATUS_ID", "EMPLOYEE_STATUS_NAME_EN", "EMPLOYEE_STATUS_NAME_AR", "DEPARTMENT_ID", "DEPARTMENT_NAME_EN", "DEPARTMENT_NAME_AR", "DEPARTMENT_CODE", "JOB_ID", "JOB_TITLE_NAME_EN", "JOB_TITLE_NAME_AR", "JOB_TITLE_CODE", "SITE_NAME_EN", "SITE_NAME_AR", "SITE_CODE", "LOCATION_ID", "LOCATION_NAME_EN", "LOCATION_NAME_AR", "LOCATION_LATITUDE", "LOCATION_LONGITUDE", "LOCATION_ZONE_TYPE", "LOCATION_ZONE_RADIUS", "MANAGER_EMPLOYEE_ID", "MANAGER_NAME_EN", "MANAGER_NAME_AR", "COMPANY_NAME", "BRANCH_NAME") AS 
  SELECT
    -- ── بيانات المستخدم (SEC_USERS) ──────────────────────────
    U.ID                        AS USER_ID,
    U.USERNAME,
    U.NAME                      AS USER_NAME_EN,
    U.NAME_AR                   AS USER_NAME_AR,
    U.PASSWORD,
    U.EMAIL,
    U.PHONE,
    U.IS_LOCKED,
    U.STATUS                    AS USER_STATUS,
    U.NOTES                     AS USER_NOTES,
    U.USER_TYPE,
    U.IS_OTP_SMS,
    U.IS_MOBILE_APP,
    U.DEFAULT_COMPANY_ID,
    U.DEFAULT_BRANCH_ID,
    U.DEVICE_UUID               AS DEVICE_UUID,
    U.IS_CHANGE_PASSWORD        AS IS_CHANGE_PASSWORD,
    U.IS_PASSWORD_CHANGED       AS IS_PASSWORD_CHANGED,
    U.PASSWORD_CHANGE_DATE      AS PASSWORD_CHANGE_DATE,
    U.ALLOW_ATTENDANCE,         -- Selected here
    U.ALLOW_DAILIES,            -- Selected here

    -- ── بيانات الموظف (HR_EMPLOYEES) ─────────────────────────
    E.EMPLOYEE_ID,
    E.CODE                      AS EMPLOYEE_CODE,
    E.ID_NUMBER,
    E.DATE_OF_BIRTH,
    E.FULL_NAME_AR              AS EMPLOYEE_NAME_AR,
    E.FULL_NAME_EN              AS EMPLOYEE_NAME_EN,
    E.HIRE_DATE,
    E.EMPLOYMENT_STATUS,
    E.WORK_LOCATION,
    E.SITE_ID,
    E.CHECK_LOCATION,

    -- ── فئة الموظف (HR_EMPLOYEE_CATEGORIES) ──────────────────
    E.EMPLOYEE_CATEGORY_ID,
    CAT.NAME                    AS EMPLOYEE_CATEGORY_NAME_EN,
    CAT.ARABIC_NAME             AS EMPLOYEE_CATEGORY_NAME_AR,

    -- ── حالة الموظف (HR_EMPLOYEE_STATUS) ─────────────────────
    E.EMPLOYMENT_STATUS         AS EMPLOYEE_STATUS_ID,
    EMP_STS.NAME                AS EMPLOYEE_STATUS_NAME_EN,
    EMP_STS.ARABIC_NAME         AS EMPLOYEE_STATUS_NAME_AR,

    -- ── القسم (HR_DEPARTMENT) ─────────────────────────────────
    E.DEPARTMENT_ID,
    DEPT.NAME                   AS DEPARTMENT_NAME_EN,
    DEPT.ARABIC_NAME            AS DEPARTMENT_NAME_AR,
    DEPT.CODE                   AS DEPARTMENT_CODE,

    -- ── المسمى الوظيفي (HR_JOB_TITLE) ────────────────────────
    E.JOB_ID,
    JOB.NAME                    AS JOB_TITLE_NAME_EN,
    JOB.ARABIC_NAME             AS JOB_TITLE_NAME_AR,
    JOB.CODE                    AS JOB_TITLE_CODE,

    -- ── الموقع (HR_SITES) ────────────────────────────────────
    SITE.NAME                   AS SITE_NAME_EN,
    SITE.ARABIC_NAME            AS SITE_NAME_AR,
    SITE.CODE                   AS SITE_CODE,

    -- ── اللوكيشن (HR_SITE_LOCATIONS) ─────────────────────────
    E.LOCATION_ID,
    LOC.NAME                    AS LOCATION_NAME_EN,
    LOC.ARABIC_NAME             AS LOCATION_NAME_AR,
    LOC.LATITUDE                AS LOCATION_LATITUDE,
    LOC.LONGITUDE               AS LOCATION_LONGITUDE,
    LOC.ZONE_TYPE               AS LOCATION_ZONE_TYPE,
    LOC.ZONE_RADIUS             AS LOCATION_ZONE_RADIUS,

    -- ── المدير المباشر (REPORTS_TO) ───────────────────────────
    E.REPORTS_TO                AS MANAGER_EMPLOYEE_ID,
    MGR.FULL_NAME_EN            AS MANAGER_NAME_EN,
    MGR.FULL_NAME_AR            AS MANAGER_NAME_AR,

    -- ── الشركة والفرع ────────────────────────────────────────
    COMP.NAME_AR                AS COMPANY_NAME,
    BRNCH.NAME_AR               AS BRANCH_NAME

FROM SEC_USERS U
LEFT JOIN HR_EMPLOYEES E
    ON U.USER_TYPE = 'EMPLOYEE'
   AND E.EMPLOYEE_ID = U.REFERENCE_USER_ID
LEFT JOIN HR_EMPLOYEE_CATEGORIES CAT
    ON CAT.ID = E.EMPLOYEE_CATEGORY_ID
LEFT JOIN HR_EMPLOYEE_STATUS EMP_STS
    ON EMP_STS.ID = E.EMPLOYMENT_STATUS
LEFT JOIN HR_DEPARTMENT DEPT
    ON DEPT.ID = E.DEPARTMENT_ID
LEFT JOIN HR_JOB_TITLE JOB
    ON JOB.ID = E.JOB_ID
LEFT JOIN HR_SITES SITE
    ON SITE.ID = E.SITE_ID
LEFT JOIN HR_SITE_LOCATIONS LOC
    ON LOC.ID = E.LOCATION_ID
LEFT JOIN HR_EMPLOYEES MGR
    ON MGR.EMPLOYEE_ID = E.REPORTS_TO
LEFT JOIN DBS_COMP COMP
    ON COMP.ID = U.DEFAULT_COMPANY_ID
LEFT JOIN DBS_BRANCHES BRNCH
    ON BRNCH.ID = U.DEFAULT_BRANCH_ID;
